### ISSUE TITLE
Creating directory exits 1 if it already exists

### ISSUE THREAD

**Issue by CoreyJ87** [andreafabrizi/Dropbox-Uploader#371] opened 2017-04-27 16:19 UTC
This seems like its unintended. As the file will still upload if the folder already exists. But CI calls the job a failure due to the exit code being 1. Due to the fact that the folder creation fails because the folder already exists

**Comment by andreafabrizi** [comment] 2017-05-26 07:10
I don't fully understand, can you provide an example pls?

**Comment by Nelluk** [comment] 2018-10-23 19:06
I'm a new user and also seeing this issue:

```shell
nelluk@n3:~$ /home/nelluk/Dropbox-Uploader/dropbox_uploader.sh -f /home/nelluk/.dropbox_uploader upload /home/nelluk/backups backups
 > Creating Directory "/backups/backups"... DONE
 > Uploading "/home/nelluk/backups/myfile_bak-201810211552.sqlc" to "/backups/backups/myfile_bak-201810211552.sqlc"... DONE
 > Uploading "/home/nelluk/backups/myfile_bak-201810220200.sqlc" to "/backups/backups/myfile_bak-201810220200.sqlc"... DONE
 > Uploading "/home/nelluk/backups/myfile_bak-201810230200.sqlc" to "/backups/backups/myfile_bak-201810230200.sqlc"... DONE
 > Uploading "/home/nelluk/backups/myfile_bak.sqlc" to "/backups/backups/myfile_bak.sqlc"... DONE
(general) nelluk@n3:~$ /home/nelluk/Dropbox-Uploader/dropbox_uploader.sh -f /home/nelluk/.dropbox_uploader upload /home/nelluk/backups backups
 > Creating Directory "/backups/backups"... FAILED
> Skipping file "/home/nelluk/backups/myfile_bak-201810211552.sqlc", file exists with the same hash
> Skipping file "/home/nelluk/backups/myfile_bak-201810220200.sqlc", file exists with the same hash
> Skipping file "/home/nelluk/backups/myfile_bak-201810230200.sqlc", file exists with the same hash
> Skipping file "/home/nelluk/backups/myfile_bak.sqlc", file exists with the same hash
Some error occured. Please check the log.
```

**Comment by nexxai** [comment] 2020-07-03 02:15
@andreafabrizi I'm seeing the same problem and I'll try and explain.

Using the "upload" command if you are uploading an entire directory, the very first time you run the command, it creates the directory no problem, but on subsequent runs, it returns an error code saying that the folder already exists, which isn't ideal since future steps in the process (outside of your script) may depend on exit code 0 to continue.  This isn't really great since all it's saying is that the folder couldn't be created because it already exists.  While I can understand that some people might appreciate that, I'm using the script simply as a backup and so I don't care that the folder already exists.

It would be nice if there was a flag like "-i" that would ignore any "file already exists" errors so that the script can continue without issue.

**Comment by MadWalnut** [comment] 2020-12-15 00:46
Same issue for me. Is there a workaround?

**Comment by mkalen** [comment] 2021-04-09 20:31
I use Dropbox-Uploader with cron and it fails all the time due to this behaviour. Since error status is "sticky", it's enough to have one single existing directory on Dropbox for the whole cron job to fail. I think I found the root cause; seems like HTTP response code returned by Dropbox API has changed from what the script expects. I will try to create a PR to fix this.

**Comment by mkalen** [comment] 2021-04-09 21:04
@andreafabrizi I have tested the change on PR#533 - it will handle existing directories with exit status 0, but will fail as expected and raise ERROR_STATUS=1 on file conflicts (i.e. when directory creation fails due to file with same name existing on Dropbox = an actual error). Works fine for my cron tests! Both types return HTTP status code 409 (conflict), script was checking for 403 which is authentication error. Returned JSON can be used to determine actual error:
Folder conflict = directory exists / no error:
`{"error_summary": "path/conflict/folder`
File conflict = file is in the way so remote directory can't be created / actual error:
`{"error_summary": "path/conflict/file`

**Comment by olimortimer** [comment] 2021-04-30 12:10
I'm trying to chain a ping back after the Dropbox-Uploader runs, to track successful cron job running, however I'm finding it's still exiting with a failure, which causes the ping back `upload && pingback` to fail.

```
 > Creating Directory "/htop"... FAILED
Some error occured. rerun the script with "-d" option and check the output and logfile: /tmp/du_resp_23928.
```

Debug output

```
{"error_summary": "path/conflict/folder/.", "error": {".tag": "path", "path": {".tag": "conflict", "conflict": {".tag": "folder"}}}}
```

Do you know when the merge request will be implemented please?

**Comment by mkalen** [comment] 2021-04-30 13:27
@olimortimer While waiting for PR merge, unless you want other fixes you can get the script or clone from fork+branch: https://github.com/mkalen/Dropbox-Uploader/tree/bugfix/371 which contains the PR code / suggested fix for this issue.

**Closed** 2021-04-30 14:52 UTC
Labels: Asked more info
